export const project = [
  {
    _id: "kt2",
    name: "Односпальная кровать",
    img: "kt2.jpg",
    visible: true,
    hits: false,
    new: false,
    sale: false,
    price: 0,
    date: "2019-06-05",
    free: true,
    category: "krovati",
  },
  {
    _id: "kh1",
    name: "Кухня прямая 2 метра 10см",
    img: "kh1.jpg",
    visible: true,
    hits: false,
    new: false,
    sale: false,
    price: 0,
    date: "2016-02-18",
    free: true,
    category: "kuhny",
  },
  {
    _id: "kd4",
    name: "Комод пеленальный",
    img: "kd4.jpg",
    visible: true,
    hits: false,
    new: false,
    sale: true,
    price: 50,
    date: "2016-02-18",
    free: false,
    category: "komodi",
  },
  {
    _id: "kd5",
    name: "Комод с дверкой",
    img: "kd5.jpg",
    visible: true,
    hits: false,
    new: false,
    sale: false,
    price: 0,
    date: "2016-03-27",
    free: true,
    category: "komodi",
  },
  {
    _id: "kt1",
    name: "Кровать двуспальная",
    img: "kt1.jpg",
    visible: true,
    hits: false,
    new: true,
    sale: true,
    price: 250,
    date: "2016-02-20",
    free: false,
    category: "krovati",
  },
  {
    _id: "kh2",
    name: "Кухня угловая",
    img: "kh2.jpg",
    visible: true,
    hits: false,
    new: false,
    sale: false,
    price: 0,
    date: "2016-02-20",
    free: true,
    category: "kuhny",
  },
  {
    _id: "p7",
    name: "Прихожая 1",
    img: "p1.jpg",
    visible: true,
    hits: false,
    new: true,
    sale: true,
    price: 100,
    date: "2016-02-20",
    free: false,
    category: "prihozhii",
  },
  {
    _id: "p8",
    name: "Прихожая 2",
    img: "p2.jpg",
    visible: true,
    hits: false,
    new: true,
    sale: true,
    price: 100,
    date: "2016-02-20",
    free: false,
    category: "prihozhii",
  },
  {
    _id: "st3",
    name: 'Стол "Эверест"',
    img: "st3.jpg",
    visible: true,
    hits: false,
    new: true,
    sale: true,
    price: 120,
    date: "2016-02-20",
    free: false,
    category: "stol-komputerniy",
  },
  {
    _id: "st1",
    name: "Офисный стол",
    img: "st1.jpg",
    visible: true,
    hits: false,
    new: false,
    sale: false,
    price: 0,
    date: "2016-03-02",
    free: true,
    category: "stoli",
  },
  {
    _id: "st2",
    name: 'Компьютерный стол "Мини"',
    img: "st2.jpg",
    visible: true,
    hits: false,
    new: false,
    sale: false,
    price: 0,
    date: "2016-03-02",
    free: true,
    category: "stoli",
  },
  {
    _id: "st5",
    name: "Стол компьютерный угловой",
    img: "st5.jpg",
    visible: true,
    hits: false,
    new: true,
    sale: false,
    price: 0,
    date: "2016-03-15",
    free: true,
    category: "stol-komputerniy",
  },
  {
    _id: "sk2",
    name: "Шкаф трёхстворчатый с антресолью",
    img: "sk2.jpg",
    visible: true,
    hits: false,
    new: false,
    sale: false,
    price: 0,
    date: "2016-03-02",
    free: true,
    category: "shkaf",
  },
  {
    _id: "sk3",
    name: "Шкаф двустворчатый с ящиками",
    img: "1.jpg",
    visible: true,
    hits: false,
    new: false,
    sale: false,
    price: 0,
    date: "2016-03-02",
    free: true,
    category: "shkaf",
  },
  {
    _id: "sk1",
    name: "Шкаф угловой 1000х1000",
    img: "1.jpg",
    visible: true,
    hits: false,
    new: false,
    sale: false,
    price: 0,
    date: "2016-03-02",
    free: true,
    category: "shkaf",
  },
  {
    _id: "sk4",
    name: "Шкаф-купе трёхстворчатый",
    img: "1.jpg",
    visible: true,
    hits: false,
    new: false,
    sale: false,
    price: 0,
    date: "2016-03-02",
    free: true,
    category: "shkaf-kupe",
  },
  {
    _id: "sk5",
    name: "Шкаф-купе двустворчатый",
    img: "1.jpg",
    visible: true,
    hits: false,
    new: false,
    sale: false,
    price: 0,
    date: "2016-03-02",
    free: true,
    category: "shkaf-kupe",
  },
  {
    _id: "tb1",
    name: "Тумбочка с двумя ящиками",
    img: "1.jpg",
    visible: true,
    hits: false,
    new: false,
    sale: false,
    price: 0,
    date: "2016-03-02",
    free: true,
    category: "tumbochka",
  },
  {
    _id: "pl1",
    name: "Полка подвесная",
    img: "1.jpg",
    visible: true,
    hits: false,
    new: true,
    sale: false,
    price: 0,
    date: "2016-03-02",
    free: true,
    category: "polki",
  },
  {
    _id: "gk1",
    name: "Горка 1",
    img: "1.jpg",
    visible: true,
    hits: false,
    new: true,
    sale: false,
    price: 0,
    date: "2016-03-12",
    free: true,
    category: "gorki",
  },
  {
    _id: "sz1",
    name: 'Столик журнальный "Лирон"',
    img: "1.jpg",
    visible: true,
    hits: false,
    new: false,
    sale: false,
    price: 0,
    date: "2016-03-13",
    free: true,
    category: "stoli-zhurnalniye",
  },
  {
    _id: "st6",
    name: "Стол-книжка 1",
    img: "1.jpg",
    visible: true,
    hits: false,
    new: false,
    sale: false,
    price: 0,
    date: "2016-03-20",
    free: true,
    category: "stol-kuhonniy",
  },
  {
    _id: "st7",
    name: "Стол-книжка 2",
    img: "1.jpg",
    visible: true,
    hits: false,
    new: false,
    sale: false,
    price: 0,
    date: "2016-03-21",
    free: true,
    category: "stol-kuhonniy",
  },
  {
    _id: "kd1",
    name: "Комод 900х900х500",
    img: "1.jpg",
    visible: true,
    hits: true,
    new: true,
    sale: false,
    price: 0,
    date: "2016-03-23",
    free: true,
    category: "komodi",
  },
  {
    _id: "p1",
    name: "Прихожая 3",
    img: "1.jpg",
    visible: true,
    hits: false,
    new: false,
    sale: false,
    price: 0,
    date: "2016-03-24",
    free: true,
    category: "prihozhii",
  },
];

const fetchAll = () =>
  new Promise((resolve) => {
    window.setTimeout(function () {
      resolve(project);
    }, 200);
  });

const projectFuncs = {
  fetchAll,
};

export default projectFuncs;
